# ==========================================
# 🌌 Lucid Void - Theme Configuration
# ==========================================

name = "Lucid Void"
license = "GPL-3.0-or-later"
licenselink = "https://github.com/AstroNomen/hugo-theme-lucidvoid/blob/main/LICENSE"
description = "A Hugo theme designed exclusively for plain text blogging. It returns the digital reading experience to its purest form by stripping away redundant visual noise."

homepage = "https://github.com/AstroNomen/hugo-theme-lucidvoid"
demosite = "https://sss.akiday.com"

tags = ["blog", "minimalist", "plain-text", "typography", "clean"]
features = ["math-typesetting", "responsive", "zero-dependency", "auto-dark-mode"]

[author]
  name = "Aki (AkiDAY.)"
  homepage = "https://akiday.com/en"